-- Add CUSTODY_ACTIVATED and CUSTODY_CANCELLED to EventType enum
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'CUSTODY_ACTIVATED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'CUSTODY_CANCELLED';
